# Generated by Django 5.2.5 on 2025-08-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('prezzo', models.FloatField()),
                ('immagine', models.ImageField(upload_to='')),
            ],
        ),
    ]
