# Generated by Django 5.2.5 on 2025-08-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0002_ordine_ordineitem_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('messaggio', models.TextField()),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
